"""Editorial search copy and useful subject groupings, maintained with the lessons."""

from update_site import LESSON_LIMIT

PAGES = {
    'ai-practice.html': ('Copy-and-Paste AI Prompts for English Practice', 'Copy complete AI prompts for English vocabulary, grammar, reading, workplace dialogues and everyday conversation. Every prompt includes the learning material.'),
    'index.html': ('Free English Lessons, Grammar & Workplace English', 'Learn English with free news lessons at three levels, 44 grammar guides, workplace dialogues, printable PDFs and practical everyday conversation activities.'),
    'efsp.html': ('English for Work: 41 Free Professional English Courses', 'Choose from 41 professional English courses with 328 workplace lessons, 368 dialogues, vocabulary, AI practice prompts and 164 free printable guides.'),
    'grammar-concepts.html': ('English Grammar Practice: 44 Lessons & Free PDFs', 'Study 44 English grammar topics with clear examples, multiple-choice exercises, answer feedback, printable workbooks and teaching guides.'),
    'archive.html': ('English News Lessons Archive: Read at Three Levels', 'Find English news lessons by date, topic or vocabulary. Read beginner, intermediate and advanced versions with grammar, comprehension questions and discussion.'),
    'beginner.html': ('Beginner English News Lessons: A1–A2 Reading Practice', f'Read the latest {LESSON_LIMIT} news lessons in beginner English. Build A1–A2 vocabulary, practice simple grammar and check your understanding with questions.'),
    'intermediate.html': ('Intermediate English News Lessons: B1–B2 Practice', f'Practice B1–B2 English with the latest {LESSON_LIMIT} news lessons. Explore useful vocabulary, grammar, comprehension questions and guided discussion.'),
    'advanced.html': ('Advanced English News Lessons: C1+ Reading Practice', f'Read the latest {LESSON_LIMIT} news lessons in advanced English. Practice nuanced vocabulary, precise grammar, critical reading and thoughtful discussion at C1+.'),
    'tools.html': ('English Practice Tools: Grammar, Speaking & Vocabulary', 'Practice English with sentence-repair activities, pronunciation shadowing, workplace phrases, tone exercises and a short learning diagnostic.'),
    'us-life.html': ('Everyday English in the US: 24 Beginner Conversation Units', 'Practice beginner English for housing, shopping, appointments, transport and daily life in the US. Explore 24 units with vocabulary and short dialogues.'),
    'about.html': ('About English Ladder: Lessons, Sources & Corrections', 'Learn how English Ladder creates and reviews its free English lessons, uses source material, explains learning levels and handles corrections.'),
    'privacy.html': ('Privacy: Your English Practice, Notes & Browser Settings', 'Understand how English Ladder handles practice notes, browser preferences, optional work-course drafts, recordings, AI prompts and site analytics.'),
    'photo-credits.html': ('Photo Credits & Illustration Sources', 'Find image sources, photographer credits and licensing details for English Ladder, including how AI illustrations are labeled in news lessons.'),
    'continue.html': ('Review Your English: Guided Practice', 'Review useful English expressions, revisit grammar and news lessons, and copy a complete AI prompt for polite requests and clarification practice.'),
    '404.html': ('Page Not Found', 'Find your next English lesson in the news archive, grammar library or English for Work courses, or return to the English Ladder homepage.'),
    'sitemap.html': ('All English Lessons: Browse Grammar, News & Work Courses', 'Browse English Ladder by subject: grammar lessons, professional English courses, news reading at three levels, everyday conversations and practice tools.'),
}

# These topics are drawn from the actual course inventories, not search-volume guesses.
WORK_TOPICS = {
    'cultural-leadership-us-branches': 'inclusive meetings, clear expectations, constructive feedback and respectful disagreement',
    'ai-development': 'AI research, model evaluation, data quality, deployment and technical team discussions',
    'general-it': 'IT support, cloud infrastructure, incident handoffs and technical troubleshooting',
    'law': 'client intake, privilege, discovery, contracts, settlement and legal workplace discussions',
    'finance': 'accounting, financial planning, treasury, audit, investment and risk discussions',
    'financial-advice': 'client discovery, risk profiles, recommendations, disclosures and retirement discussions',
    'marketing': 'campaign briefs, audience strategy, attribution, brand risk and marketing reports',
    'real-estate': 'buyer consultations, offers, disclosures, financing and property transactions',
    'corporate-strategy': 'strategic tradeoffs, growth, portfolio choices, uncertainty and board presentations',
    'pharmaceutical': 'clinical trials, drug safety, regulatory discussions, quality and medical affairs',
    'healthcare-administration': 'patient flow, staffing, service recovery, care coordination and executive reporting',
    'nursing-allied-health': 'clinical handoffs, patient education, documentation and team communication',
    'biotechnology': 'assay design, biomarkers, research evidence, partnerships and investor updates',
    'medical-devices': 'design controls, risk management, usability, quality systems and complaint handling',
    'manufacturing': 'production meetings, defects, maintenance, supplier quality and shift handoffs',
    'supply-chain-logistics': 'forecasting, inventory, purchasing, shipping delays and supplier communication',
    'human-resources': 'hiring, onboarding, performance feedback, employee relations and workplace policies',
    'project-management': 'scope, schedules, dependencies, project risks and stakeholder updates',
    'engineering': 'design reviews, requirements, testing, failure analysis and technical tradeoffs',
    'semiconductor': 'wafer fabrication, lithography, yield, process integration and foundry communication',
    'software-product-management': 'product discovery, roadmaps, prioritization, launches and stakeholder negotiation',
    'cybersecurity': 'incident response, vulnerability triage, threat modeling and security briefings',
    'data-analytics-business-intelligence': 'data quality, dashboards, metric definitions, experiments and insight presentations',
    'education-administration': 'enrollment, student support, parent communication and institutional decisions',
    'higher-education-research': 'grant proposals, lab meetings, peer review, authorship and academic presentations',
    'hospitality-tourism': 'reservations, guest complaints, service recovery, events and hotel operations',
    'aviation': 'operations control, maintenance coordination, ground handling and incident reporting',
    'construction-architecture': 'design coordination, RFIs, change orders, site meetings and client communication',
    'energy-utilities': 'outages, grid reliability, infrastructure projects and customer communication',
    'environmental-consulting': 'site assessments, sampling, permitting, remediation and client risk discussions',
    'insurance': 'underwriting, claims, coverage, broker communication and customer escalations',
    'banking-operations': 'payment exceptions, loan operations, fraud concerns, audits and banking complaints',
    'retail-ecommerce': 'inventory, fulfillment, returns, customer complaints and vendor coordination',
    'media-entertainment': 'creative development, production planning, rights, distribution and audience metrics',
    'telecommunications': 'network outages, service provisioning, deployment and technical coordination',
    'government-public-administration': 'public meetings, procurement, grants and interagency communication',
    'nonprofit-ngo': 'donor communication, grants, program evaluation and community partnerships',
    'consulting': 'client discovery, scope, recommendations, implementation risks and executive presentations',
    'sales-business-development': 'sales discovery, objections, pricing, procurement and partnership negotiation',
    'customer-success': 'customer onboarding, adoption, escalations, renewals and product feedback',
    'legal-operations-compliance': 'contract workflows, audits, investigations, privacy requests and governance',
}

CATEGORIES = {
    'Business & professional services': {
        'slug': 'business-professional', 'title': 'Business and Professional English',
        'description': 'Practice business English for finance, law, strategy, HR, projects and client services. Choose free workplace lessons, professional dialogues and printable PDFs.',
        'intro': 'A useful business message makes the purpose, evidence and next step clear. These courses help you explain a recommendation, question an assumption, negotiate a constraint and respond professionally when expectations differ.',
        'choose': 'Start with the course that matches your responsibilities. Finance and financial advice cover different audiences; law and legal operations focus on different kinds of work. Consulting, strategy and project management offer practice for cross-functional conversations. Human resources and leadership courses focus on expectations, feedback and participation.',
        'practice': 'Read a case and identify what the speaker can confirm. Give a brief response before looking at the model. Then ask a partner to challenge one assumption or request a clearer next step. Finish with a short written message for the same reader.',
        'grammar': [9, 16, 17, 44],
    },
    'Technology & data': {
        'slug': 'technology-data', 'title': 'English for Technology and Data Teams',
        'description': 'Build technical English for IT, AI, cybersecurity, engineering, data analytics, software products and semiconductors, with realistic dialogues and free PDFs.',
        'intro': 'Technical communication connects specialist knowledge with decisions other people can understand. Practice explaining a result, separating evidence from a hypothesis, clarifying requirements and handing over an unresolved issue.',
        'choose': 'Choose general IT for service and infrastructure conversations, cybersecurity for risk and incident communication, or AI development for model and research discussions. Engineering, semiconductor, product management and data analytics each provide their own cases and terminology.',
        'practice': 'Study a dialogue and underline an expression that qualifies a claim or asks for evidence. Recreate the conversation without the script, keeping the numbers and uncertainty accurate. Try a second version for a colleague who does not share your technical vocabulary.',
        'grammar': [9, 16, 42, 43],
    },
    'Health & life sciences': {
        'slug': 'health-life-sciences', 'title': 'English for Healthcare and Life Sciences',
        'description': 'Practice professional English for nursing, healthcare administration, biotechnology, medical devices and pharmaceuticals through cases, dialogues and free PDFs.',
        'intro': 'Healthcare and life-science communication often depends on carefully stating what is known, what is pending and who needs to respond. These materials develop the English used in handoffs, research discussions, quality conversations and professional coordination.',
        'choose': 'Nursing and allied health emphasizes team and patient-facing communication. Healthcare administration focuses on services and operations. Biotechnology, medical devices and pharmaceutical courses address distinct research, development, quality and regulatory communication settings.',
        'practice': 'Read the case and separate observations from conclusions. Rehearse a handoff, ask one precise clarification question, and repeat back the open item. Treat every scenario as fictional language practice; actual clinical, regulatory and safety decisions follow qualified supervision and applicable procedures.',
        'grammar': [14, 16, 28, 42],
    },
    'Industry & infrastructure': {
        'slug': 'industry-infrastructure', 'title': 'English for Industry and Infrastructure',
        'description': 'Practice English for manufacturing, logistics, aviation, construction, energy, environmental work and telecoms, with workplace dialogues and printable guides.',
        'intro': 'An operational update needs a clear status, a specific problem and an accurate next action. Practice the language of production meetings, service interruptions, design coordination, shipping delays and other situations where teams depend on shared information.',
        'choose': 'Select the field closest to your daily work. Manufacturing and logistics focus on flow, quality and coordination. Construction and engineering-related conversations require precise scope and design language. Aviation, energy, environmental consulting and telecommunications bring different operational contexts.',
        'practice': 'Give a short update that distinguishes completed work from pending checks. Have a partner introduce a delay or missing record and ask you to clarify its effect. Preserve the stated facts and approval limits. These lessons practice communication and do not replace authorized operating or safety procedures.',
        'grammar': [1, 14, 16, 43],
    },
    'Customers & creative work': {
        'slug': 'customers-creative', 'title': 'English for Customers, Sales and Creative Work',
        'description': 'Improve English for sales, marketing, hospitality, retail, customer success, real estate and media through realistic conversations, exercises and free PDFs.',
        'intro': 'Customer and creative conversations combine clear information with an appropriate tone. Practice understanding a request, explaining a limitation, handling an objection and agreeing on a useful next step without promising an outcome you cannot control.',
        'choose': 'Choose hospitality or retail for service situations, sales for discovery and negotiation, or customer success for adoption and renewals. Marketing, media and real estate courses each introduce their own terminology, audiences and professional scenarios.',
        'practice': 'Read both sides of a dialogue and identify what each speaker needs. Switch roles, change one fictional constraint and rehearse a new ending. Follow the conversation with a concise written message that preserves its commitments and any unresolved questions.',
        'grammar': [3, 17, 36, 44],
    },
    'Education & public service': {
        'slug': 'education-public-service', 'title': 'English for Education and Public Service',
        'description': 'Practice English for education, research, public administration and nonprofit work, with professional vocabulary, realistic dialogues and free teaching materials.',
        'intro': 'Education and public-service communication brings together people with different responsibilities and expectations. Practice explaining evidence, inviting a missing perspective, discussing limited resources and clarifying how a decision will be made.',
        'choose': 'Education administration focuses on institutional and student-support communication. Higher education and research covers academic collaboration and research discussions. Public administration and nonprofit courses address community-facing work, grants, coordination and accountability.',
        'practice': 'Prepare a short explanation for a specific audience, then ask a partner to raise a concern that has not been considered. Clarify which points are agreed and which still need review. Close with a written summary that names the next question or action.',
        'grammar': [9, 12, 17, 44],
    },
}

# A small, reviewed bridge from recurring communication moves to relevant grammar.
FUNCTION_GRAMMAR = {
    'clarify': [28, 42, 44], 'qualify': [8, 25, 37],
    'compare': [27, 22, 43], 'update': [14, 15, 16],
    'request': [15, 29, 44], 'negotiate': [32, 17, 41],
    'handoff': [14, 28, 15], 'repair': [24, 36, 28],
    'facilitate': [17, 44, 12], 'explain': [42, 9, 30],
    'feedback': [17, 24, 38], 'pushback': [41, 32, 25],
}
